DROP DATABASE IF EXISTS EmployeeDB;

CREATE DATABASE EmployeeDB;

USE EmployeeDB;


CREATE TABLE departments (
id INTEGER NOT NULL AUTO_INCREMENT,
department VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE roles (
id INTEGER NOT NULL AUTO_INCREMENT,
title VARCHAR(50) NOT NULL,
salary DECIMAL(10,2) NOT NULL,
department_id INTEGER,
PRIMARY KEY (id),
FOREIGN KEY (department_id) REFERENCES departments(id)
);


CREATE TABLE employees (
id INTEGER NOT NULL AUTO_INCREMENT,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER NOT NULL,
manager_id INTEGER,
PRIMARY KEY (id),
FOREIGN KEY (role_id) REFERENCES roles(id),
FOREIGN KEY (manager_id) REFERENCES employees(id)
);